apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tekton-monitor
  labels:
    release: prometheus
    app: tekton-pipelines-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-pipelines
spec:
  selector:
    matchLabels:
      app: tekton-pipelines-controller
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: tekton-pipelines
  endpoints:
  - port: http-metrics
  namespaceSelector:
    matchNames:
    - tekton-pipelines

