apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot-services

bases:
 - ../base

namePrefix: ccp-

commonLabels:
  lang: go
  app: service-name

images:
  - name: iot-image
    newName: harbor.iotpadmin.iot.io/iot-development/iot-service-name

configMapGenerator:
  - name: configmap-envs
    behavior: merge
    literals:
      - PORT="5050"

secretGenerator:
  - name: secret-envs
    behavior: merge
    type: Opaque
    #files:
