apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ccp
spec:
  replicas: 2
  version: "6.0.0"
  adminCredentials: ccp
  configuration: 
    automation.versions.source: local
    statefulSet: |
      spec:
        template:
          spec:
            containers:
              - name: mongodb-ops-manager
                volumeMounts:
                - name: mongodb-versions
                  mountPath: /mongodb-ops-manager/mongodb-releases
            volumeClaimTemplates:
              - metadata:
                  name: mongodb-versions
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  resources:
                    requests:
                      storage: "20Gi"
  backup:
    enabled: false
  applicationDatabase:
    members: 3
    version: 5.0.7-ent
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: ccp
spec:
  version: "4.2.2-ent"
  opsManager:
    configMapRef:
      name: ccp
  credentials: ccp
  type: Standalone
  persistent: true
