apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: opsmgr
  namespace: develop
spec:
  replicas: 1
  version: 4.2.1
  adminCredentials: adminusercredentials
  externalConnectivity:
    type: NodePort  
  applicationDatabase:
    members: 3
    version: 4.2.1
    persistent: true